###########spring related properties########################
spring:
  application:
    name: rabbit-mq-consumer
    
server.port: 0
###########spring related properties########################

###########rabbit connection details###################
rabbit:
  mq:
    connection-properties:
      addresses: ec2-13-233-146-34.ap-south-1.compute.amazonaws.com:5672
      virtual-host: dev-host
      user: mq-admin
      password: mq-admin
    queue-a:
      auto-startup: true 
      concurrency: 1-10
    queue-b:
      auto-startup: true
      concurrency: 1-10
    queue-c:
      auto-startup: true
      concurrency: 1-10
###########rabbit connection details###################